SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `xy_inc_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `xy_inc_db` ;

-- -----------------------------------------------------
-- Table `xy_inc_db`.`POI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xy_inc_db`.`POI` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `COORD_X` BIGINT NOT NULL,
  `COORD_Y` BIGINT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `xy_inc_db`.`POI` (`NAME`,`COORD_X`,`COORD_Y`) VALUES ("Lanchonete",27,12);
INSERT INTO `xy_inc_db`.`POI` (`NAME`,`COORD_X`,`COORD_Y`) VALUES ("Posto",31,18);
INSERT INTO `xy_inc_db`.`POI` (`NAME`,`COORD_X`,`COORD_Y`) VALUES ("Joalheria",15,12);
INSERT INTO `xy_inc_db`.`POI` (`NAME`,`COORD_X`,`COORD_Y`) VALUES ("Floricultura",19,21);
INSERT INTO `xy_inc_db`.`POI` (`NAME`,`COORD_X`,`COORD_Y`) VALUES ("Pub",12,8);
INSERT INTO `xy_inc_db`.`POI` (`NAME`,`COORD_X`,`COORD_Y`) VALUES ("Supermercado",23,6);
INSERT INTO `xy_inc_db`.`POI` (`NAME`,`COORD_X`,`COORD_Y`) VALUES ("Churrascaria",28,2);
